### ISSUE TITLE
 Smashed the stack: 0

### ISSUE THREAD

**Issue by kawaegle** [DavidBuchanan314/fusee-nano#8]
run it with latest hetake and got that 

[+] Read 109500 bytes from hekate_ctcaer_6.2.1.bin
[+] Sent 0x2b000 bytes
[+] Smashed the stack: 0

and the payload dont trigger the boot file what does it mean ?
 I guess patched swich

**Comment by DavidBuchanan314** [comment]
It does likely mean your switch is patched

**Comment by blah1** [comment]
I had this today. Hekate 6.2.2. Switch serial XAW10008****** (so I was sure it wasn't patched, but I just got it second hand last week and I'm new to all this). 

It worked about 10-20% of the time (I was starting to give up hope by the time it finally worked).
I got the same output whether it worked or failed though, both said "Smashed the stack: 0".

I switched to another USB port (a blue 3.0 port instead of the red USB 3.1 port I was using before), and it seems to be working 100% of the time now, so I assume I have a driver/hardware issue on those ports. It still says "Smashed the stack: 0" though.

I'm running "Pop! OS" (based on Ubuntu 22.04), so it could likely be related to some package of that. "xxd -n" failed in the Makefile because my version of xxd is from 2021 (though that was easy enough to do manually).
